Remove Appcelerator references
feedhenry/feedhenry.org pull request #6
Opened 2017-03-31 11:48 UTC by sedroche

We are removing the appcelerator app from the studio. Removing all references in the repos also

2017-04-07 11:54 UTC, jcesarmobile commented
I found this about AeroGear-Push-Titanium https://github.com/feedhenry/feedhenry.github.io/blob/master/_data/feedhenry-repos.json#L2-L8

It's not displayed on the website, but should be good to remove it

2017-04-18 11:24 UTC, pb82 approved these changes
LGTM. ping @pmdarrow

2017-04-26 15:32 UTC, pmdarrow requested changes
Just one small fix, otherwise LGTM!

2017-04-26 15:32 UTC, pmdarrow commented on _data/feedhenry-repos.json
> -    "AeroGear-Push-Titanium": {
This data will just get pulled back in when `_get_repo_data.py` is run again, so I'd remove this change. As long as you're not referencing "AeroGear-Push-Titanium" in any templates, it won't get shown.

2017-04-26 15:39 UTC, pmdarrow approved these changes

2017-04-26 15:39 UTC, merged